import type { Groupe, TypeExercice } from "./types";

/**
 * Bibliothèque d'exercices — 131 entrées.
 *
 * FICHIER GÉNÉRÉ. Ne pas éditer à la main : modifier
 * scripts/generer-seed-exercices.py puis relancer
 * `python3 scripts/generer-exercices-ts.py`.
 *
 * La même liste alimente la migration SQL `..._seed_exercices.sql`, conservée
 * dans le dépôt pour le jour où les données repasseront par une base. Les deux
 * sorties viennent de la même source : elles ne peuvent pas diverger.
 *
 * L'identifiant d'un exercice global **est** son slug. C'est stable, lisible
 * dans les exports, et ça survit à un changement de moteur de stockage — ce
 * qu'un UUID généré à l'installation ne ferait pas.
 */
export type FicheExercice = {
  id: string;
  nom: string;
  slug: string;
  groupe_principal: Groupe;
  groupes_secondaires: Groupe[];
  equipement: string;
  type: TypeExercice;
  instructions: string;
};

export const EXERCICES: readonly FicheExercice[] = [
  { id: "developpe-couche", nom: "Développé couché", slug: "developpe-couche", groupe_principal: "pectoraux", groupes_secondaires: ["triceps", "epaules"], equipement: "barre_olympique", type: "charge", instructions: "Omoplates serrées, barre au niveau des mamelons, coudes à 45° du buste." },
  { id: "developpe-couche-halteres", nom: "Développé couché haltères", slug: "developpe-couche-halteres", groupe_principal: "pectoraux", groupes_secondaires: ["triceps", "epaules"], equipement: "halteres", type: "charge", instructions: "Descends jusqu'à sentir l'étirement, poignets alignés au-dessus des coudes." },
  { id: "developpe-incline-barre", nom: "Développé incliné barre", slug: "developpe-incline-barre", groupe_principal: "pectoraux", groupes_secondaires: ["epaules", "triceps"], equipement: "barre_olympique", type: "charge", instructions: "Banc à 30°, au-delà c'est l'épaule qui travaille." },
  { id: "developpe-incline-halteres", nom: "Développé incliné haltères", slug: "developpe-incline-halteres", groupe_principal: "pectoraux", groupes_secondaires: ["epaules", "triceps"], equipement: "halteres", type: "charge", instructions: "Banc à 30°, haltères qui se rapprochent sans se toucher en haut." },
  { id: "developpe-decline-halteres", nom: "Développé décliné haltères", slug: "developpe-decline-halteres", groupe_principal: "pectoraux", groupes_secondaires: ["triceps"], equipement: "halteres", type: "charge", instructions: "Pieds bloqués, trajectoire vers le bas des pectoraux." },
  { id: "ecarte-couche-halteres", nom: "Écarté couché haltères", slug: "ecarte-couche-halteres", groupe_principal: "pectoraux", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Coudes légèrement fléchis et figés : le mouvement vient de l'épaule." },
  { id: "ecarte-incline-halteres", nom: "Écarté incliné haltères", slug: "ecarte-incline-halteres", groupe_principal: "pectoraux", groupes_secondaires: ["epaules"], equipement: "halteres", type: "charge", instructions: "Banc à 30°, arrête la descente quand l'épaule commence à rouler en avant." },
  { id: "ecarte-a-la-poulie", nom: "Écarté à la poulie", slug: "ecarte-a-la-poulie", groupe_principal: "pectoraux", groupes_secondaires: [], equipement: "poulie", type: "charge", instructions: "Buste légèrement penché, mains qui se croisent devant le nombril." },
  { id: "pompes", nom: "Pompes", slug: "pompes", groupe_principal: "pectoraux", groupes_secondaires: ["triceps", "abdominaux"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Corps gainé d'une ligne, coudes à 45°, poitrine qui frôle le sol." },
  { id: "pompes-lestees", nom: "Pompes lestées", slug: "pompes-lestees", groupe_principal: "pectoraux", groupes_secondaires: ["triceps"], equipement: "poids_du_corps", type: "charge", instructions: "Disque posé au milieu du dos, même gainage qu'à vide." },
  { id: "pompes-pieds-sureleves", nom: "Pompes pieds surélevés", slug: "pompes-pieds-sureleves", groupe_principal: "pectoraux", groupes_secondaires: ["epaules", "triceps"], equipement: "banc", type: "poids_du_corps", instructions: "Pieds sur le banc : la charge se déplace vers le haut des pectoraux." },
  { id: "dips-pectoraux", nom: "Dips pectoraux", slug: "dips-pectoraux", groupe_principal: "pectoraux", groupes_secondaires: ["triceps", "epaules"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Buste penché en avant, descente jusqu'à l'horizontale du bras." },
  { id: "pull-over-haltere", nom: "Pull-over haltère", slug: "pull-over-haltere", groupe_principal: "pectoraux", groupes_secondaires: ["dos"], equipement: "halteres", type: "charge", instructions: "Bras quasi tendus, haltère qui passe derrière la tête sans creuser les lombaires." },
  { id: "ecarte-elastique-debout", nom: "Écarté élastique debout", slug: "ecarte-elastique-debout", groupe_principal: "pectoraux", groupes_secondaires: ["epaules"], equipement: "elastique", type: "charge", instructions: "Élastique dans le dos, mains qui se rejoignent à hauteur de poitrine." },
  { id: "developpe-au-sol", nom: "Développé au sol", slug: "developpe-au-sol", groupe_principal: "pectoraux", groupes_secondaires: ["triceps"], equipement: "halteres", type: "charge", instructions: "Coudes qui touchent le sol : amplitude réduite, épaule protégée." },
  { id: "traction-pronation", nom: "Traction pronation", slug: "traction-pronation", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "barre_traction", type: "poids_du_corps", instructions: "Mains plus larges que les épaules, menton au-dessus de la barre sans à-coup." },
  { id: "traction-supination", nom: "Traction supination", slug: "traction-supination", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "barre_traction", type: "poids_du_corps", instructions: "Paumes vers toi : plus de biceps, plus de charge possible." },
  { id: "traction-prise-neutre", nom: "Traction prise neutre", slug: "traction-prise-neutre", groupe_principal: "dos", groupes_secondaires: ["biceps", "avant_bras"], equipement: "barre_traction", type: "poids_du_corps", instructions: "Paumes face à face, la prise la plus douce pour l'épaule." },
  { id: "traction-lestee", nom: "Traction lestée", slug: "traction-lestee", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "barre_traction", type: "charge", instructions: "Ceinture de lest ou haltère entre les pieds, amplitude complète obligatoire." },
  { id: "tirage-horizontal-barre-basse", nom: "Tirage horizontal barre basse", slug: "tirage-horizontal-barre-basse", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "barre_traction", type: "poids_du_corps", instructions: "Corps gainé sous la barre, poitrine qui vient toucher." },
  { id: "rowing-barre", nom: "Rowing barre", slug: "rowing-barre", groupe_principal: "dos", groupes_secondaires: ["biceps", "lombaires"], equipement: "barre_olympique", type: "charge", instructions: "Buste à 45°, barre tirée vers le nombril, dos plat du début à la fin." },
  { id: "rowing-haltere-un-bras", nom: "Rowing haltère un bras", slug: "rowing-haltere-un-bras", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "halteres", type: "charge", instructions: "Appui main et genou sur le banc, coude qui longe le corps." },
  { id: "rowing-t-barre", nom: "Rowing T barre", slug: "rowing-t-barre", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "barre_olympique", type: "charge", instructions: "Une extrémité de barre calée dans un coin, tirage vers le sternum." },
  { id: "rowing-kettlebell", nom: "Rowing kettlebell", slug: "rowing-kettlebell", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "kettlebell", type: "charge", instructions: "Hanches hautes, tirage explosif, descente contrôlée." },
  { id: "tirage-vertical-poulie", nom: "Tirage vertical poulie", slug: "tirage-vertical-poulie", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "poulie", type: "charge", instructions: "Poitrine sortie, barre qui descend vers le haut des pectoraux." },
  { id: "tirage-horizontal-poulie", nom: "Tirage horizontal poulie", slug: "tirage-horizontal-poulie", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "poulie", type: "charge", instructions: "Buste fixe, omoplates qui se resserrent avant que les bras plient." },
  { id: "tirage-bras-tendus-poulie", nom: "Tirage bras tendus poulie", slug: "tirage-bras-tendus-poulie", groupe_principal: "dos", groupes_secondaires: [], equipement: "poulie", type: "charge", instructions: "Bras tendus, mouvement uniquement à l'épaule, on sent les grands dorsaux." },
  { id: "rowing-elastique", nom: "Rowing élastique", slug: "rowing-elastique", groupe_principal: "dos", groupes_secondaires: ["biceps"], equipement: "elastique", type: "charge", instructions: "Élastique ancré devant, coudes le long du corps." },
  { id: "souleve-de-terre", nom: "Soulevé de terre", slug: "souleve-de-terre", groupe_principal: "dos", groupes_secondaires: ["ischios", "fessiers", "lombaires"], equipement: "barre_olympique", type: "charge", instructions: "Barre contre les tibias, dos neutre, on pousse le sol avec les jambes." },
  { id: "rack-pull", nom: "Rack pull", slug: "rack-pull", groupe_principal: "dos", groupes_secondaires: ["lombaires", "ischios"], equipement: "rack", type: "charge", instructions: "Barre départ genoux : on charge lourd sur la partie haute du soulevé." },
  { id: "shrugs-barre", nom: "Shrugs barre", slug: "shrugs-barre", groupe_principal: "dos", groupes_secondaires: ["avant_bras"], equipement: "barre_olympique", type: "charge", instructions: "Épaules vers les oreilles, pas de rotation, pause en haut." },
  { id: "shrugs-halteres", nom: "Shrugs haltères", slug: "shrugs-halteres", groupe_principal: "dos", groupes_secondaires: ["avant_bras"], equipement: "halteres", type: "charge", instructions: "Bras relâchés, seules les épaules montent." },
  { id: "face-pull-poulie", nom: "Face pull poulie", slug: "face-pull-poulie", groupe_principal: "dos", groupes_secondaires: ["epaules"], equipement: "poulie", type: "charge", instructions: "Corde tirée vers le front, coudes hauts : l'exercice qui répare les épaules." },
  { id: "good-morning", nom: "Good morning", slug: "good-morning", groupe_principal: "ischios", groupes_secondaires: ["lombaires", "fessiers"], equipement: "barre_olympique", type: "charge", instructions: "Barre sur les trapèzes, hanches en arrière, genoux à peine fléchis." },
  { id: "developpe-militaire", nom: "Développé militaire", slug: "developpe-militaire", groupe_principal: "epaules", groupes_secondaires: ["triceps"], equipement: "barre_olympique", type: "charge", instructions: "Debout, fessiers et abdos serrés, barre qui passe devant le front." },
  { id: "developpe-halteres-assis", nom: "Développé haltères assis", slug: "developpe-halteres-assis", groupe_principal: "epaules", groupes_secondaires: ["triceps"], equipement: "halteres", type: "charge", instructions: "Dossier vertical, haltères qui montent sans se cogner." },
  { id: "developpe-arnold", nom: "Développé Arnold", slug: "developpe-arnold", groupe_principal: "epaules", groupes_secondaires: ["triceps"], equipement: "halteres", type: "charge", instructions: "Rotation des poignets pendant la montée, paumes vers l'avant en haut." },
  { id: "developpe-kettlebell-un-bras", nom: "Développé kettlebell un bras", slug: "developpe-kettlebell-un-bras", groupe_principal: "epaules", groupes_secondaires: ["triceps", "abdominaux"], equipement: "kettlebell", type: "charge", instructions: "Poignet neutre, gainage anti-inclinaison sur le côté opposé." },
  { id: "elevations-laterales", nom: "Élévations latérales", slug: "elevations-laterales", groupe_principal: "epaules", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Montée jusqu'à l'horizontale, petits doigts légèrement plus hauts." },
  { id: "elevations-laterales-elastique", nom: "Élévations latérales élastique", slug: "elevations-laterales-elastique", groupe_principal: "epaules", groupes_secondaires: [], equipement: "elastique", type: "charge", instructions: "Tension dès le départ, descente freinée sur trois secondes." },
  { id: "elevations-frontales", nom: "Élévations frontales", slug: "elevations-frontales", groupe_principal: "epaules", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Un bras après l'autre, pas d'élan du bassin." },
  { id: "oiseau-halteres", nom: "Oiseau haltères", slug: "oiseau-halteres", groupe_principal: "epaules", groupes_secondaires: ["dos"], equipement: "halteres", type: "charge", instructions: "Buste penché à l'horizontale, coudes qui partent vers l'arrière." },
  { id: "rotations-externes-elastique", nom: "Rotations externes élastique", slug: "rotations-externes-elastique", groupe_principal: "epaules", groupes_secondaires: [], equipement: "elastique", type: "charge", instructions: "Coude collé au corps, mouvement lent : c'est de la prévention, pas de la force." },
  { id: "tirage-menton", nom: "Tirage menton", slug: "tirage-menton", groupe_principal: "epaules", groupes_secondaires: ["dos"], equipement: "barre_olympique", type: "charge", instructions: "Prise largeur d'épaules, coudes qui montent en premier, arrêt au sternum." },
  { id: "pompes-piquees", nom: "Pompes piquées", slug: "pompes-piquees", groupe_principal: "epaules", groupes_secondaires: ["triceps"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Bassin haut, tête qui descend entre les mains." },
  { id: "handstand-push-up", nom: "Handstand push-up", slug: "handstand-push-up", groupe_principal: "epaules", groupes_secondaires: ["triceps"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Contre un mur, gainage complet, descente jusqu'au contact du crâne." },
  { id: "curl-barre", nom: "Curl barre", slug: "curl-barre", groupe_principal: "biceps", groupes_secondaires: ["avant_bras"], equipement: "barre_olympique", type: "charge", instructions: "Coudes fixes contre les côtes, aucun balancement du buste." },
  { id: "curl-halteres-alterne", nom: "Curl haltères alterné", slug: "curl-halteres-alterne", groupe_principal: "biceps", groupes_secondaires: ["avant_bras"], equipement: "halteres", type: "charge", instructions: "Supination progressive pendant la montée." },
  { id: "curl-marteau", nom: "Curl marteau", slug: "curl-marteau", groupe_principal: "biceps", groupes_secondaires: ["avant_bras"], equipement: "halteres", type: "charge", instructions: "Prise neutre, on travaille le brachial et l'épaisseur du bras." },
  { id: "curl-incline", nom: "Curl incliné", slug: "curl-incline", groupe_principal: "biceps", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Banc à 45°, bras qui pendent derrière le corps : étirement maximal." },
  { id: "curl-concentre", nom: "Curl concentré", slug: "curl-concentre", groupe_principal: "biceps", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Coude calé sur la cuisse, contraction tenue une seconde en haut." },
  { id: "curl-araignee", nom: "Curl araignée", slug: "curl-araignee", groupe_principal: "biceps", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Buste sur banc incliné, bras à la verticale, zéro triche possible." },
  { id: "curl-poulie-basse", nom: "Curl poulie basse", slug: "curl-poulie-basse", groupe_principal: "biceps", groupes_secondaires: [], equipement: "poulie", type: "charge", instructions: "Tension continue du début à la fin, contrairement à la barre." },
  { id: "curl-elastique", nom: "Curl élastique", slug: "curl-elastique", groupe_principal: "biceps", groupes_secondaires: [], equipement: "elastique", type: "charge", instructions: "Pieds sur l'élastique, résistance croissante vers le haut." },
  { id: "curl-zottman", nom: "Curl Zottman", slug: "curl-zottman", groupe_principal: "biceps", groupes_secondaires: ["avant_bras"], equipement: "halteres", type: "charge", instructions: "Montée en supination, descente en pronation." },
  { id: "barre-au-front", nom: "Barre au front", slug: "barre-au-front", groupe_principal: "triceps", groupes_secondaires: [], equipement: "barre_olympique", type: "charge", instructions: "Coudes fixes pointés au plafond, barre qui descend au-dessus du front." },
  { id: "developpe-couche-prise-serree", nom: "Développé couché prise serrée", slug: "developpe-couche-prise-serree", groupe_principal: "triceps", groupes_secondaires: ["pectoraux"], equipement: "barre_olympique", type: "charge", instructions: "Mains largeur d'épaules, coudes serrés le long du buste." },
  { id: "extension-nuque-haltere", nom: "Extension nuque haltère", slug: "extension-nuque-haltere", groupe_principal: "triceps", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Haltère à deux mains derrière la tête, coudes qui restent serrés." },
  { id: "extension-poulie-corde", nom: "Extension poulie corde", slug: "extension-poulie-corde", groupe_principal: "triceps", groupes_secondaires: [], equipement: "poulie", type: "charge", instructions: "Coudes collés, écartement de la corde en fin de mouvement." },
  { id: "kickback-haltere", nom: "Kickback haltère", slug: "kickback-haltere", groupe_principal: "triceps", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Bras parallèle au sol, seul l'avant-bras bouge." },
  { id: "dips-triceps-sur-banc", nom: "Dips triceps sur banc", slug: "dips-triceps-sur-banc", groupe_principal: "triceps", groupes_secondaires: ["epaules"], equipement: "banc", type: "poids_du_corps", instructions: "Mains derrière soi sur le banc, coudes vers l'arrière et non vers l'extérieur." },
  { id: "pompes-diamant", nom: "Pompes diamant", slug: "pompes-diamant", groupe_principal: "triceps", groupes_secondaires: ["pectoraux"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Index et pouces en losange sous le sternum." },
  { id: "extension-elastique", nom: "Extension élastique", slug: "extension-elastique", groupe_principal: "triceps", groupes_secondaires: [], equipement: "elastique", type: "charge", instructions: "Élastique fixé en hauteur, coudes verrouillés le long du corps." },
  { id: "curl-poignet", nom: "Curl poignet", slug: "curl-poignet", groupe_principal: "avant_bras", groupes_secondaires: [], equipement: "barre_olympique", type: "charge", instructions: "Avant-bras posés sur les cuisses, seules les mains bougent." },
  { id: "curl-poignet-inverse", nom: "Curl poignet inversé", slug: "curl-poignet-inverse", groupe_principal: "avant_bras", groupes_secondaires: [], equipement: "barre_olympique", type: "charge", instructions: "Paumes vers le bas, charge légère : les extenseurs sont fragiles." },
  { id: "suspension-a-la-barre", nom: "Suspension à la barre", slug: "suspension-a-la-barre", groupe_principal: "avant_bras", groupes_secondaires: ["dos"], equipement: "barre_traction", type: "temps", instructions: "Suspendu bras tendus, épaules actives, on tient le chrono." },
  { id: "farmer-s-carry", nom: "Farmer's carry", slug: "farmer-s-carry", groupe_principal: "avant_bras", groupes_secondaires: ["corps_entier", "abdominaux"], equipement: "kettlebell", type: "distance", instructions: "Charges lourdes dans chaque main, buste droit, pas réguliers." },
  { id: "squat-barre", nom: "Squat barre", slug: "squat-barre", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers", "lombaires"], equipement: "rack", type: "charge", instructions: "Descente jusqu'à la cuisse parallèle au sol minimum, genoux dans l'axe des pieds." },
  { id: "front-squat", nom: "Front squat", slug: "front-squat", groupe_principal: "quadriceps", groupes_secondaires: ["abdominaux", "fessiers"], equipement: "rack", type: "charge", instructions: "Coudes hauts, barre sur les deltoïdes avant, buste le plus vertical possible." },
  { id: "squat-gobelet", nom: "Squat gobelet", slug: "squat-gobelet", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers"], equipement: "kettlebell", type: "charge", instructions: "Kettlebell contre la poitrine, coudes à l'intérieur des genoux en bas." },
  { id: "fentes-avant", nom: "Fentes avant", slug: "fentes-avant", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers", "ischios"], equipement: "halteres", type: "charge", instructions: "Genou arrière qui frôle le sol, buste vertical." },
  { id: "fentes-marchees", nom: "Fentes marchées", slug: "fentes-marchees", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers"], equipement: "halteres", type: "charge", instructions: "On avance à chaque répétition, pas de pause entre les pas." },
  { id: "fentes-bulgares", nom: "Fentes bulgares", slug: "fentes-bulgares", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers"], equipement: "banc", type: "charge", instructions: "Pied arrière sur le banc, tout le poids sur la jambe avant." },
  { id: "step-up-sur-banc", nom: "Step-up sur banc", slug: "step-up-sur-banc", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers"], equipement: "banc", type: "charge", instructions: "Poussée uniquement avec la jambe posée sur le banc, pas d'élan." },
  { id: "squat-saute", nom: "Squat sauté", slug: "squat-saute", groupe_principal: "quadriceps", groupes_secondaires: ["mollets", "cardio"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Réception amortie, genoux souples, enchaînement rythmé." },
  { id: "hack-squat-barre", nom: "Hack squat barre", slug: "hack-squat-barre", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers"], equipement: "barre_olympique", type: "charge", instructions: "Barre derrière les mollets, talons légèrement surélevés." },
  { id: "sissy-squat", nom: "Sissy squat", slug: "sissy-squat", groupe_principal: "quadriceps", groupes_secondaires: [], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Genoux qui avancent, bassin en ligne avec les épaules, très exigeant." },
  { id: "chaise-au-mur", nom: "Chaise au mur", slug: "chaise-au-mur", groupe_principal: "quadriceps", groupes_secondaires: [], equipement: "poids_du_corps", type: "temps", instructions: "Dos plaqué au mur, cuisses à l'horizontale, on tient." },
  { id: "squat-elastique", nom: "Squat élastique", slug: "squat-elastique", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers"], equipement: "elastique", type: "charge", instructions: "Élastique sous les pieds et sur les épaules, tension maximale en haut." },
  { id: "pistol-squat", nom: "Pistol squat", slug: "pistol-squat", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers", "abdominaux"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Squat sur une jambe, l'autre tendue devant, contrôle total de la descente." },
  { id: "souleve-de-terre-roumain", nom: "Soulevé de terre roumain", slug: "souleve-de-terre-roumain", groupe_principal: "ischios", groupes_secondaires: ["fessiers", "lombaires"], equipement: "barre_olympique", type: "charge", instructions: "Barre qui glisse le long des cuisses, hanches loin en arrière." },
  { id: "souleve-de-terre-jambes-tendues", nom: "Soulevé de terre jambes tendues", slug: "souleve-de-terre-jambes-tendues", groupe_principal: "ischios", groupes_secondaires: ["lombaires"], equipement: "halteres", type: "charge", instructions: "Genoux très légèrement fléchis, descente jusqu'à l'étirement, pas plus bas." },
  { id: "souleve-de-terre-sumo", nom: "Soulevé de terre sumo", slug: "souleve-de-terre-sumo", groupe_principal: "ischios", groupes_secondaires: ["fessiers", "quadriceps"], equipement: "barre_olympique", type: "charge", instructions: "Pieds larges, mains à l'intérieur des genoux, buste plus vertical." },
  { id: "leg-curl-nordique", nom: "Leg curl nordique", slug: "leg-curl-nordique", groupe_principal: "ischios", groupes_secondaires: [], equipement: "tapis", type: "poids_du_corps", instructions: "Chevilles bloquées, descente freinée le plus longtemps possible." },
  { id: "hip-thrust", nom: "Hip thrust", slug: "hip-thrust", groupe_principal: "fessiers", groupes_secondaires: ["ischios"], equipement: "banc", type: "charge", instructions: "Omoplates sur le banc, menton rentré, extension complète des hanches en haut." },
  { id: "hip-thrust-une-jambe", nom: "Hip thrust une jambe", slug: "hip-thrust-une-jambe", groupe_principal: "fessiers", groupes_secondaires: ["ischios"], equipement: "banc", type: "poids_du_corps", instructions: "Une jambe en l'air, bassin qui reste horizontal." },
  { id: "pont-fessier-au-sol", nom: "Pont fessier au sol", slug: "pont-fessier-au-sol", groupe_principal: "fessiers", groupes_secondaires: ["ischios"], equipement: "tapis", type: "poids_du_corps", instructions: "Pression dans les talons, pause d'une seconde en haut." },
  { id: "kettlebell-swing", nom: "Kettlebell swing", slug: "kettlebell-swing", groupe_principal: "fessiers", groupes_secondaires: ["ischios", "dos", "cardio"], equipement: "kettlebell", type: "charge", instructions: "Mouvement de hanche, pas de squat : la kettlebell est projetée, pas soulevée." },
  { id: "abduction-elastique", nom: "Abduction élastique", slug: "abduction-elastique", groupe_principal: "fessiers", groupes_secondaires: [], equipement: "elastique", type: "charge", instructions: "Élastique au-dessus des genoux, ouverture lente et contrôlée." },
  { id: "donkey-kick-elastique", nom: "Donkey kick élastique", slug: "donkey-kick-elastique", groupe_principal: "fessiers", groupes_secondaires: [], equipement: "elastique", type: "charge", instructions: "Dos neutre, talon poussé vers le plafond." },
  { id: "good-morning-elastique", nom: "Good morning élastique", slug: "good-morning-elastique", groupe_principal: "ischios", groupes_secondaires: ["lombaires"], equipement: "elastique", type: "charge", instructions: "Version légère du good morning, idéale en échauffement." },
  { id: "mollets-debout-barre", nom: "Mollets debout barre", slug: "mollets-debout-barre", groupe_principal: "mollets", groupes_secondaires: [], equipement: "barre_olympique", type: "charge", instructions: "Amplitude complète : étirement en bas, pause en haut." },
  { id: "mollets-debout-halteres", nom: "Mollets debout haltères", slug: "mollets-debout-halteres", groupe_principal: "mollets", groupes_secondaires: [], equipement: "halteres", type: "charge", instructions: "Avant-pieds sur un disque, talons qui descendent sous le niveau." },
  { id: "mollets-une-jambe", nom: "Mollets une jambe", slug: "mollets-une-jambe", groupe_principal: "mollets", groupes_secondaires: [], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Une jambe à la fois, l'autre repliée, pas d'appui pour tricher." },
  { id: "mollets-assis", nom: "Mollets assis", slug: "mollets-assis", groupe_principal: "mollets", groupes_secondaires: [], equipement: "banc", type: "charge", instructions: "Disque sur les genoux, on cible le soléaire." },
  { id: "gainage-planche", nom: "Gainage planche", slug: "gainage-planche", groupe_principal: "abdominaux", groupes_secondaires: ["lombaires"], equipement: "tapis", type: "temps", instructions: "Coudes sous les épaules, fessiers serrés, aucune cambrure." },
  { id: "gainage-lateral", nom: "Gainage latéral", slug: "gainage-lateral", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "tapis", type: "temps", instructions: "Hanche haute, corps aligné vu de face." },
  { id: "hollow-hold", nom: "Hollow hold", slug: "hollow-hold", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "tapis", type: "temps", instructions: "Bas du dos plaqué au sol, bras et jambes tendus." },
  { id: "releve-de-jambes-suspendu", nom: "Relevé de jambes suspendu", slug: "releve-de-jambes-suspendu", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "barre_traction", type: "poids_du_corps", instructions: "Jambes tendues jusqu'à l'horizontale, pas de balancement." },
  { id: "releve-de-genoux-suspendu", nom: "Relevé de genoux suspendu", slug: "releve-de-genoux-suspendu", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "barre_traction", type: "poids_du_corps", instructions: "Genoux vers la poitrine, bassin qui s'enroule en fin de course." },
  { id: "crunch-au-sol", nom: "Crunch au sol", slug: "crunch-au-sol", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "tapis", type: "poids_du_corps", instructions: "On décolle les omoplates, pas tout le dos, nuque relâchée." },
  { id: "crunch-poulie-haute", nom: "Crunch poulie haute", slug: "crunch-poulie-haute", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "poulie", type: "charge", instructions: "À genoux, on enroule la colonne vertèbre par vertèbre." },
  { id: "rollout-a-la-barre", nom: "Rollout à la barre", slug: "rollout-a-la-barre", groupe_principal: "abdominaux", groupes_secondaires: ["lombaires"], equipement: "barre_olympique", type: "poids_du_corps", instructions: "À genoux, barre qui roule loin devant, dos qui ne creuse jamais." },
  { id: "russian-twist", nom: "Russian twist", slug: "russian-twist", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "kettlebell", type: "poids_du_corps", instructions: "Pieds décollés, rotation qui vient du buste et non des bras." },
  { id: "mountain-climber", nom: "Mountain climber", slug: "mountain-climber", groupe_principal: "abdominaux", groupes_secondaires: ["cardio"], equipement: "tapis", type: "temps", instructions: "Position de pompe, genoux qui alternent vite, bassin stable." },
  { id: "dead-bug", nom: "Dead bug", slug: "dead-bug", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "tapis", type: "poids_du_corps", instructions: "Bras et jambe opposés qui s'allongent, lombaires collées au sol." },
  { id: "pallof-press", nom: "Pallof press", slug: "pallof-press", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "elastique", type: "charge", instructions: "Élastique sur le côté, on résiste à la rotation : c'est un anti-mouvement." },
  { id: "v-ups", nom: "V-ups", slug: "v-ups", groupe_principal: "abdominaux", groupes_secondaires: [], equipement: "tapis", type: "poids_du_corps", instructions: "Bras et jambes qui se rejoignent au-dessus du bassin." },
  { id: "extension-lombaire-au-sol", nom: "Extension lombaire au sol", slug: "extension-lombaire-au-sol", groupe_principal: "lombaires", groupes_secondaires: ["fessiers"], equipement: "tapis", type: "poids_du_corps", instructions: "Buste décollé sans à-coup, regard vers le sol." },
  { id: "superman", nom: "Superman", slug: "superman", groupe_principal: "lombaires", groupes_secondaires: ["fessiers"], equipement: "tapis", type: "temps", instructions: "Bras et jambes décollés en même temps, tenue du chrono." },
  { id: "bird-dog", nom: "Bird dog", slug: "bird-dog", groupe_principal: "lombaires", groupes_secondaires: ["abdominaux"], equipement: "tapis", type: "poids_du_corps", instructions: "Bras et jambe opposés à l'horizontale, bassin qui ne bascule pas." },
  { id: "corde-a-sauter", nom: "Corde à sauter", slug: "corde-a-sauter", groupe_principal: "cardio", groupes_secondaires: ["mollets"], equipement: "corde_a_sauter", type: "temps", instructions: "Sauts bas, poignets qui tournent, coudes près du corps." },
  { id: "burpee", nom: "Burpee", slug: "burpee", groupe_principal: "cardio", groupes_secondaires: ["corps_entier"], equipement: "poids_du_corps", type: "poids_du_corps", instructions: "Poitrine au sol, saut avec les mains au-dessus de la tête." },
  { id: "burpee-broad-jump", nom: "Burpee broad jump", slug: "burpee-broad-jump", groupe_principal: "cardio", groupes_secondaires: ["corps_entier"], equipement: "poids_du_corps", type: "distance", instructions: "Burpee suivi d'un saut en longueur, on compte la distance parcourue." },
  { id: "wall-balls", nom: "Wall balls", slug: "wall-balls", groupe_principal: "corps_entier", groupes_secondaires: ["quadriceps", "epaules"], equipement: "medecine_ball", type: "charge", instructions: "Squat complet puis lancer contre la cible, on rattrape en descendant." },
  { id: "sled-push", nom: "Sled push", slug: "sled-push", groupe_principal: "corps_entier", groupes_secondaires: ["quadriceps", "fessiers"], equipement: "traineau", type: "distance", instructions: "Bras tendus, buste incliné, petits pas rapides et continus." },
  { id: "sled-pull", nom: "Sled pull", slug: "sled-pull", groupe_principal: "corps_entier", groupes_secondaires: ["dos", "ischios"], equipement: "traineau", type: "distance", instructions: "Tirage à la corde, recul régulier, dos plat." },
  { id: "sandbag-lunges", nom: "Sandbag lunges", slug: "sandbag-lunges", groupe_principal: "quadriceps", groupes_secondaires: ["fessiers", "corps_entier"], equipement: "sac", type: "distance", instructions: "Sac sur les épaules, genou arrière au sol à chaque pas." },
  { id: "ski-erg", nom: "Ski erg", slug: "ski-erg", groupe_principal: "cardio", groupes_secondaires: ["dos", "abdominaux"], equipement: "ski_erg", type: "distance", instructions: "Extension complète de hanche à chaque tirage, bras qui finissent le long du corps." },
  { id: "rameur", nom: "Rameur", slug: "rameur", groupe_principal: "cardio", groupes_secondaires: ["dos", "quadriceps"], equipement: "rameur", type: "distance", instructions: "Jambes, buste, bras dans cet ordre ; retour dans l'ordre inverse." },
  { id: "course-a-pied", nom: "Course à pied", slug: "course-a-pied", groupe_principal: "cardio", groupes_secondaires: ["mollets", "ischios"], equipement: "poids_du_corps", type: "distance", instructions: "Allure régulière, foulée courte, cadence élevée." },
  { id: "thruster", nom: "Thruster", slug: "thruster", groupe_principal: "corps_entier", groupes_secondaires: ["quadriceps", "epaules"], equipement: "barre_olympique", type: "charge", instructions: "Front squat enchaîné à un développé, un seul mouvement fluide." },
  { id: "epaule", nom: "Épaulé", slug: "epaule", groupe_principal: "corps_entier", groupes_secondaires: ["quadriceps", "dos"], equipement: "barre_olympique", type: "charge", instructions: "Tirage explosif puis passage sous la barre, coudes projetés vers l'avant." },
  { id: "epaule-jete", nom: "Épaulé-jeté", slug: "epaule-jete", groupe_principal: "corps_entier", groupes_secondaires: ["epaules", "quadriceps"], equipement: "barre_olympique", type: "charge", instructions: "Épaulé, puis impulsion des jambes pour envoyer la barre au-dessus de la tête." },
  { id: "arrache-kettlebell", nom: "Arraché kettlebell", slug: "arrache-kettlebell", groupe_principal: "corps_entier", groupes_secondaires: ["epaules", "dos"], equipement: "kettlebell", type: "charge", instructions: "Un seul mouvement du sol au bras tendu, poignet qui pivote sans claquer." },
  { id: "turkish-get-up", nom: "Turkish get-up", slug: "turkish-get-up", groupe_principal: "corps_entier", groupes_secondaires: ["abdominaux", "epaules"], equipement: "kettlebell", type: "charge", instructions: "Du sol à debout, kettlebell toujours à la verticale, regard dessus." },
  { id: "man-maker", nom: "Man maker", slug: "man-maker", groupe_principal: "corps_entier", groupes_secondaires: ["pectoraux", "epaules"], equipement: "halteres", type: "charge", instructions: "Pompe, rowing des deux côtés, puis développé debout : une seule répétition." },
  { id: "devil-press", nom: "Devil press", slug: "devil-press", groupe_principal: "corps_entier", groupes_secondaires: ["epaules", "cardio"], equipement: "halteres", type: "charge", instructions: "Burpee haltères en main puis passage direct au-dessus de la tête." },
  { id: "box-jump", nom: "Box jump", slug: "box-jump", groupe_principal: "quadriceps", groupes_secondaires: ["mollets", "cardio"], equipement: "banc", type: "poids_du_corps", instructions: "Réception complète sur la box avant l'extension, descente en marchant." },
  { id: "bear-crawl", nom: "Bear crawl", slug: "bear-crawl", groupe_principal: "corps_entier", groupes_secondaires: ["abdominaux", "epaules"], equipement: "poids_du_corps", type: "distance", instructions: "Genoux à deux centimètres du sol, déplacement bras et jambe opposés." },
  { id: "marche-gobelet", nom: "Marche gobelet", slug: "marche-gobelet", groupe_principal: "corps_entier", groupes_secondaires: ["abdominaux", "quadriceps"], equipement: "kettlebell", type: "distance", instructions: "Kettlebell contre la poitrine, buste vertical, respiration régulière." },
] as const;

const PAR_ID = new Map(EXERCICES.map((e) => [e.id, e]));

export function exerciceParId(id: string): FicheExercice | undefined {
  return PAR_ID.get(id);
}

/** Recherche insensible à la casse et aux accents, filtrable par groupe. */
export function chercher(terme: string, groupe?: Groupe | null): FicheExercice[] {
  const normalise = (t: string) =>
    t.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const cible = normalise(terme.trim());
  return EXERCICES.filter(
    (e) => (!groupe || e.groupe_principal === groupe) && (!cible || normalise(e.nom).includes(cible)),
  );
}

/** Exercices réalisables avec le matériel déclaré. Le poids du corps est toujours disponible. */
export function filtrerParMateriel(materiel: readonly string[]): FicheExercice[] {
  const dispo = new Set([...materiel, "poids_du_corps"]);
  return EXERCICES.filter((e) => dispo.has(e.equipement));
}
