-- ═══════════════════════════════════════════════════════════════════════
-- FONTE — bibliothèque d'exercices (131 entrées)
--
-- FICHIER GÉNÉRÉ. Ne pas éditer à la main : modifier
-- scripts/generer-seed-exercices.py puis relancer le script.
--
-- Les exercices Hyrox référencent du matériel absent du garage (traîneau,
-- rameur, ski erg, medecine ball, sac). C'est volontaire : l'onboarding filtre
-- sur le matériel déclaré, ces mouvements n'apparaissent donc que pour qui les
-- coche. Voir DECISIONS.md.
-- ═══════════════════════════════════════════════════════════════════════

insert into public.exercices
  (nom, slug, groupe_principal, groupes_secondaires, equipement, type, instructions)
values
  ('Développé couché', 'developpe-couche', 'pectoraux', array['triceps', 'epaules'], 'barre_olympique', 'charge'::public.type_exercice, 'Omoplates serrées, barre au niveau des mamelons, coudes à 45° du buste.'),
  ('Développé couché haltères', 'developpe-couche-halteres', 'pectoraux', array['triceps', 'epaules'], 'halteres', 'charge'::public.type_exercice, 'Descends jusqu''à sentir l''étirement, poignets alignés au-dessus des coudes.'),
  ('Développé incliné barre', 'developpe-incline-barre', 'pectoraux', array['epaules', 'triceps'], 'barre_olympique', 'charge'::public.type_exercice, 'Banc à 30°, au-delà c''est l''épaule qui travaille.'),
  ('Développé incliné haltères', 'developpe-incline-halteres', 'pectoraux', array['epaules', 'triceps'], 'halteres', 'charge'::public.type_exercice, 'Banc à 30°, haltères qui se rapprochent sans se toucher en haut.'),
  ('Développé décliné haltères', 'developpe-decline-halteres', 'pectoraux', array['triceps'], 'halteres', 'charge'::public.type_exercice, 'Pieds bloqués, trajectoire vers le bas des pectoraux.'),
  ('Écarté couché haltères', 'ecarte-couche-halteres', 'pectoraux', '{}', 'halteres', 'charge'::public.type_exercice, 'Coudes légèrement fléchis et figés : le mouvement vient de l''épaule.'),
  ('Écarté incliné haltères', 'ecarte-incline-halteres', 'pectoraux', array['epaules'], 'halteres', 'charge'::public.type_exercice, 'Banc à 30°, arrête la descente quand l''épaule commence à rouler en avant.'),
  ('Écarté à la poulie', 'ecarte-a-la-poulie', 'pectoraux', '{}', 'poulie', 'charge'::public.type_exercice, 'Buste légèrement penché, mains qui se croisent devant le nombril.'),
  ('Pompes', 'pompes', 'pectoraux', array['triceps', 'abdominaux'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Corps gainé d''une ligne, coudes à 45°, poitrine qui frôle le sol.'),
  ('Pompes lestées', 'pompes-lestees', 'pectoraux', array['triceps'], 'poids_du_corps', 'charge'::public.type_exercice, 'Disque posé au milieu du dos, même gainage qu''à vide.'),
  ('Pompes pieds surélevés', 'pompes-pieds-sureleves', 'pectoraux', array['epaules', 'triceps'], 'banc', 'poids_du_corps'::public.type_exercice, 'Pieds sur le banc : la charge se déplace vers le haut des pectoraux.'),
  ('Dips pectoraux', 'dips-pectoraux', 'pectoraux', array['triceps', 'epaules'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Buste penché en avant, descente jusqu''à l''horizontale du bras.'),
  ('Pull-over haltère', 'pull-over-haltere', 'pectoraux', array['dos'], 'halteres', 'charge'::public.type_exercice, 'Bras quasi tendus, haltère qui passe derrière la tête sans creuser les lombaires.'),
  ('Écarté élastique debout', 'ecarte-elastique-debout', 'pectoraux', array['epaules'], 'elastique', 'charge'::public.type_exercice, 'Élastique dans le dos, mains qui se rejoignent à hauteur de poitrine.'),
  ('Développé au sol', 'developpe-au-sol', 'pectoraux', array['triceps'], 'halteres', 'charge'::public.type_exercice, 'Coudes qui touchent le sol : amplitude réduite, épaule protégée.'),
  ('Traction pronation', 'traction-pronation', 'dos', array['biceps'], 'barre_traction', 'poids_du_corps'::public.type_exercice, 'Mains plus larges que les épaules, menton au-dessus de la barre sans à-coup.'),
  ('Traction supination', 'traction-supination', 'dos', array['biceps'], 'barre_traction', 'poids_du_corps'::public.type_exercice, 'Paumes vers toi : plus de biceps, plus de charge possible.'),
  ('Traction prise neutre', 'traction-prise-neutre', 'dos', array['biceps', 'avant_bras'], 'barre_traction', 'poids_du_corps'::public.type_exercice, 'Paumes face à face, la prise la plus douce pour l''épaule.'),
  ('Traction lestée', 'traction-lestee', 'dos', array['biceps'], 'barre_traction', 'charge'::public.type_exercice, 'Ceinture de lest ou haltère entre les pieds, amplitude complète obligatoire.'),
  ('Tirage horizontal barre basse', 'tirage-horizontal-barre-basse', 'dos', array['biceps'], 'barre_traction', 'poids_du_corps'::public.type_exercice, 'Corps gainé sous la barre, poitrine qui vient toucher.'),
  ('Rowing barre', 'rowing-barre', 'dos', array['biceps', 'lombaires'], 'barre_olympique', 'charge'::public.type_exercice, 'Buste à 45°, barre tirée vers le nombril, dos plat du début à la fin.'),
  ('Rowing haltère un bras', 'rowing-haltere-un-bras', 'dos', array['biceps'], 'halteres', 'charge'::public.type_exercice, 'Appui main et genou sur le banc, coude qui longe le corps.'),
  ('Rowing T barre', 'rowing-t-barre', 'dos', array['biceps'], 'barre_olympique', 'charge'::public.type_exercice, 'Une extrémité de barre calée dans un coin, tirage vers le sternum.'),
  ('Rowing kettlebell', 'rowing-kettlebell', 'dos', array['biceps'], 'kettlebell', 'charge'::public.type_exercice, 'Hanches hautes, tirage explosif, descente contrôlée.'),
  ('Tirage vertical poulie', 'tirage-vertical-poulie', 'dos', array['biceps'], 'poulie', 'charge'::public.type_exercice, 'Poitrine sortie, barre qui descend vers le haut des pectoraux.'),
  ('Tirage horizontal poulie', 'tirage-horizontal-poulie', 'dos', array['biceps'], 'poulie', 'charge'::public.type_exercice, 'Buste fixe, omoplates qui se resserrent avant que les bras plient.'),
  ('Tirage bras tendus poulie', 'tirage-bras-tendus-poulie', 'dos', '{}', 'poulie', 'charge'::public.type_exercice, 'Bras tendus, mouvement uniquement à l''épaule, on sent les grands dorsaux.'),
  ('Rowing élastique', 'rowing-elastique', 'dos', array['biceps'], 'elastique', 'charge'::public.type_exercice, 'Élastique ancré devant, coudes le long du corps.'),
  ('Soulevé de terre', 'souleve-de-terre', 'dos', array['ischios', 'fessiers', 'lombaires'], 'barre_olympique', 'charge'::public.type_exercice, 'Barre contre les tibias, dos neutre, on pousse le sol avec les jambes.'),
  ('Rack pull', 'rack-pull', 'dos', array['lombaires', 'ischios'], 'rack', 'charge'::public.type_exercice, 'Barre départ genoux : on charge lourd sur la partie haute du soulevé.'),
  ('Shrugs barre', 'shrugs-barre', 'dos', array['avant_bras'], 'barre_olympique', 'charge'::public.type_exercice, 'Épaules vers les oreilles, pas de rotation, pause en haut.'),
  ('Shrugs haltères', 'shrugs-halteres', 'dos', array['avant_bras'], 'halteres', 'charge'::public.type_exercice, 'Bras relâchés, seules les épaules montent.'),
  ('Face pull poulie', 'face-pull-poulie', 'dos', array['epaules'], 'poulie', 'charge'::public.type_exercice, 'Corde tirée vers le front, coudes hauts : l''exercice qui répare les épaules.'),
  ('Good morning', 'good-morning', 'ischios', array['lombaires', 'fessiers'], 'barre_olympique', 'charge'::public.type_exercice, 'Barre sur les trapèzes, hanches en arrière, genoux à peine fléchis.'),
  ('Développé militaire', 'developpe-militaire', 'epaules', array['triceps'], 'barre_olympique', 'charge'::public.type_exercice, 'Debout, fessiers et abdos serrés, barre qui passe devant le front.'),
  ('Développé haltères assis', 'developpe-halteres-assis', 'epaules', array['triceps'], 'halteres', 'charge'::public.type_exercice, 'Dossier vertical, haltères qui montent sans se cogner.'),
  ('Développé Arnold', 'developpe-arnold', 'epaules', array['triceps'], 'halteres', 'charge'::public.type_exercice, 'Rotation des poignets pendant la montée, paumes vers l''avant en haut.'),
  ('Développé kettlebell un bras', 'developpe-kettlebell-un-bras', 'epaules', array['triceps', 'abdominaux'], 'kettlebell', 'charge'::public.type_exercice, 'Poignet neutre, gainage anti-inclinaison sur le côté opposé.'),
  ('Élévations latérales', 'elevations-laterales', 'epaules', '{}', 'halteres', 'charge'::public.type_exercice, 'Montée jusqu''à l''horizontale, petits doigts légèrement plus hauts.'),
  ('Élévations latérales élastique', 'elevations-laterales-elastique', 'epaules', '{}', 'elastique', 'charge'::public.type_exercice, 'Tension dès le départ, descente freinée sur trois secondes.'),
  ('Élévations frontales', 'elevations-frontales', 'epaules', '{}', 'halteres', 'charge'::public.type_exercice, 'Un bras après l''autre, pas d''élan du bassin.'),
  ('Oiseau haltères', 'oiseau-halteres', 'epaules', array['dos'], 'halteres', 'charge'::public.type_exercice, 'Buste penché à l''horizontale, coudes qui partent vers l''arrière.'),
  ('Rotations externes élastique', 'rotations-externes-elastique', 'epaules', '{}', 'elastique', 'charge'::public.type_exercice, 'Coude collé au corps, mouvement lent : c''est de la prévention, pas de la force.'),
  ('Tirage menton', 'tirage-menton', 'epaules', array['dos'], 'barre_olympique', 'charge'::public.type_exercice, 'Prise largeur d''épaules, coudes qui montent en premier, arrêt au sternum.'),
  ('Pompes piquées', 'pompes-piquees', 'epaules', array['triceps'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Bassin haut, tête qui descend entre les mains.'),
  ('Handstand push-up', 'handstand-push-up', 'epaules', array['triceps'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Contre un mur, gainage complet, descente jusqu''au contact du crâne.'),
  ('Curl barre', 'curl-barre', 'biceps', array['avant_bras'], 'barre_olympique', 'charge'::public.type_exercice, 'Coudes fixes contre les côtes, aucun balancement du buste.'),
  ('Curl haltères alterné', 'curl-halteres-alterne', 'biceps', array['avant_bras'], 'halteres', 'charge'::public.type_exercice, 'Supination progressive pendant la montée.'),
  ('Curl marteau', 'curl-marteau', 'biceps', array['avant_bras'], 'halteres', 'charge'::public.type_exercice, 'Prise neutre, on travaille le brachial et l''épaisseur du bras.'),
  ('Curl incliné', 'curl-incline', 'biceps', '{}', 'halteres', 'charge'::public.type_exercice, 'Banc à 45°, bras qui pendent derrière le corps : étirement maximal.'),
  ('Curl concentré', 'curl-concentre', 'biceps', '{}', 'halteres', 'charge'::public.type_exercice, 'Coude calé sur la cuisse, contraction tenue une seconde en haut.'),
  ('Curl araignée', 'curl-araignee', 'biceps', '{}', 'halteres', 'charge'::public.type_exercice, 'Buste sur banc incliné, bras à la verticale, zéro triche possible.'),
  ('Curl poulie basse', 'curl-poulie-basse', 'biceps', '{}', 'poulie', 'charge'::public.type_exercice, 'Tension continue du début à la fin, contrairement à la barre.'),
  ('Curl élastique', 'curl-elastique', 'biceps', '{}', 'elastique', 'charge'::public.type_exercice, 'Pieds sur l''élastique, résistance croissante vers le haut.'),
  ('Curl Zottman', 'curl-zottman', 'biceps', array['avant_bras'], 'halteres', 'charge'::public.type_exercice, 'Montée en supination, descente en pronation.'),
  ('Barre au front', 'barre-au-front', 'triceps', '{}', 'barre_olympique', 'charge'::public.type_exercice, 'Coudes fixes pointés au plafond, barre qui descend au-dessus du front.'),
  ('Développé couché prise serrée', 'developpe-couche-prise-serree', 'triceps', array['pectoraux'], 'barre_olympique', 'charge'::public.type_exercice, 'Mains largeur d''épaules, coudes serrés le long du buste.'),
  ('Extension nuque haltère', 'extension-nuque-haltere', 'triceps', '{}', 'halteres', 'charge'::public.type_exercice, 'Haltère à deux mains derrière la tête, coudes qui restent serrés.'),
  ('Extension poulie corde', 'extension-poulie-corde', 'triceps', '{}', 'poulie', 'charge'::public.type_exercice, 'Coudes collés, écartement de la corde en fin de mouvement.'),
  ('Kickback haltère', 'kickback-haltere', 'triceps', '{}', 'halteres', 'charge'::public.type_exercice, 'Bras parallèle au sol, seul l''avant-bras bouge.'),
  ('Dips triceps sur banc', 'dips-triceps-sur-banc', 'triceps', array['epaules'], 'banc', 'poids_du_corps'::public.type_exercice, 'Mains derrière soi sur le banc, coudes vers l''arrière et non vers l''extérieur.'),
  ('Pompes diamant', 'pompes-diamant', 'triceps', array['pectoraux'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Index et pouces en losange sous le sternum.'),
  ('Extension élastique', 'extension-elastique', 'triceps', '{}', 'elastique', 'charge'::public.type_exercice, 'Élastique fixé en hauteur, coudes verrouillés le long du corps.'),
  ('Curl poignet', 'curl-poignet', 'avant_bras', '{}', 'barre_olympique', 'charge'::public.type_exercice, 'Avant-bras posés sur les cuisses, seules les mains bougent.'),
  ('Curl poignet inversé', 'curl-poignet-inverse', 'avant_bras', '{}', 'barre_olympique', 'charge'::public.type_exercice, 'Paumes vers le bas, charge légère : les extenseurs sont fragiles.'),
  ('Suspension à la barre', 'suspension-a-la-barre', 'avant_bras', array['dos'], 'barre_traction', 'temps'::public.type_exercice, 'Suspendu bras tendus, épaules actives, on tient le chrono.'),
  ('Farmer''s carry', 'farmer-s-carry', 'avant_bras', array['corps_entier', 'abdominaux'], 'kettlebell', 'distance'::public.type_exercice, 'Charges lourdes dans chaque main, buste droit, pas réguliers.'),
  ('Squat barre', 'squat-barre', 'quadriceps', array['fessiers', 'lombaires'], 'rack', 'charge'::public.type_exercice, 'Descente jusqu''à la cuisse parallèle au sol minimum, genoux dans l''axe des pieds.'),
  ('Front squat', 'front-squat', 'quadriceps', array['abdominaux', 'fessiers'], 'rack', 'charge'::public.type_exercice, 'Coudes hauts, barre sur les deltoïdes avant, buste le plus vertical possible.'),
  ('Squat gobelet', 'squat-gobelet', 'quadriceps', array['fessiers'], 'kettlebell', 'charge'::public.type_exercice, 'Kettlebell contre la poitrine, coudes à l''intérieur des genoux en bas.'),
  ('Fentes avant', 'fentes-avant', 'quadriceps', array['fessiers', 'ischios'], 'halteres', 'charge'::public.type_exercice, 'Genou arrière qui frôle le sol, buste vertical.'),
  ('Fentes marchées', 'fentes-marchees', 'quadriceps', array['fessiers'], 'halteres', 'charge'::public.type_exercice, 'On avance à chaque répétition, pas de pause entre les pas.'),
  ('Fentes bulgares', 'fentes-bulgares', 'quadriceps', array['fessiers'], 'banc', 'charge'::public.type_exercice, 'Pied arrière sur le banc, tout le poids sur la jambe avant.'),
  ('Step-up sur banc', 'step-up-sur-banc', 'quadriceps', array['fessiers'], 'banc', 'charge'::public.type_exercice, 'Poussée uniquement avec la jambe posée sur le banc, pas d''élan.'),
  ('Squat sauté', 'squat-saute', 'quadriceps', array['mollets', 'cardio'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Réception amortie, genoux souples, enchaînement rythmé.'),
  ('Hack squat barre', 'hack-squat-barre', 'quadriceps', array['fessiers'], 'barre_olympique', 'charge'::public.type_exercice, 'Barre derrière les mollets, talons légèrement surélevés.'),
  ('Sissy squat', 'sissy-squat', 'quadriceps', '{}', 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Genoux qui avancent, bassin en ligne avec les épaules, très exigeant.'),
  ('Chaise au mur', 'chaise-au-mur', 'quadriceps', '{}', 'poids_du_corps', 'temps'::public.type_exercice, 'Dos plaqué au mur, cuisses à l''horizontale, on tient.'),
  ('Squat élastique', 'squat-elastique', 'quadriceps', array['fessiers'], 'elastique', 'charge'::public.type_exercice, 'Élastique sous les pieds et sur les épaules, tension maximale en haut.'),
  ('Pistol squat', 'pistol-squat', 'quadriceps', array['fessiers', 'abdominaux'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Squat sur une jambe, l''autre tendue devant, contrôle total de la descente.'),
  ('Soulevé de terre roumain', 'souleve-de-terre-roumain', 'ischios', array['fessiers', 'lombaires'], 'barre_olympique', 'charge'::public.type_exercice, 'Barre qui glisse le long des cuisses, hanches loin en arrière.'),
  ('Soulevé de terre jambes tendues', 'souleve-de-terre-jambes-tendues', 'ischios', array['lombaires'], 'halteres', 'charge'::public.type_exercice, 'Genoux très légèrement fléchis, descente jusqu''à l''étirement, pas plus bas.'),
  ('Soulevé de terre sumo', 'souleve-de-terre-sumo', 'ischios', array['fessiers', 'quadriceps'], 'barre_olympique', 'charge'::public.type_exercice, 'Pieds larges, mains à l''intérieur des genoux, buste plus vertical.'),
  ('Leg curl nordique', 'leg-curl-nordique', 'ischios', '{}', 'tapis', 'poids_du_corps'::public.type_exercice, 'Chevilles bloquées, descente freinée le plus longtemps possible.'),
  ('Hip thrust', 'hip-thrust', 'fessiers', array['ischios'], 'banc', 'charge'::public.type_exercice, 'Omoplates sur le banc, menton rentré, extension complète des hanches en haut.'),
  ('Hip thrust une jambe', 'hip-thrust-une-jambe', 'fessiers', array['ischios'], 'banc', 'poids_du_corps'::public.type_exercice, 'Une jambe en l''air, bassin qui reste horizontal.'),
  ('Pont fessier au sol', 'pont-fessier-au-sol', 'fessiers', array['ischios'], 'tapis', 'poids_du_corps'::public.type_exercice, 'Pression dans les talons, pause d''une seconde en haut.'),
  ('Kettlebell swing', 'kettlebell-swing', 'fessiers', array['ischios', 'dos', 'cardio'], 'kettlebell', 'charge'::public.type_exercice, 'Mouvement de hanche, pas de squat : la kettlebell est projetée, pas soulevée.'),
  ('Abduction élastique', 'abduction-elastique', 'fessiers', '{}', 'elastique', 'charge'::public.type_exercice, 'Élastique au-dessus des genoux, ouverture lente et contrôlée.'),
  ('Donkey kick élastique', 'donkey-kick-elastique', 'fessiers', '{}', 'elastique', 'charge'::public.type_exercice, 'Dos neutre, talon poussé vers le plafond.'),
  ('Good morning élastique', 'good-morning-elastique', 'ischios', array['lombaires'], 'elastique', 'charge'::public.type_exercice, 'Version légère du good morning, idéale en échauffement.'),
  ('Mollets debout barre', 'mollets-debout-barre', 'mollets', '{}', 'barre_olympique', 'charge'::public.type_exercice, 'Amplitude complète : étirement en bas, pause en haut.'),
  ('Mollets debout haltères', 'mollets-debout-halteres', 'mollets', '{}', 'halteres', 'charge'::public.type_exercice, 'Avant-pieds sur un disque, talons qui descendent sous le niveau.'),
  ('Mollets une jambe', 'mollets-une-jambe', 'mollets', '{}', 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Une jambe à la fois, l''autre repliée, pas d''appui pour tricher.'),
  ('Mollets assis', 'mollets-assis', 'mollets', '{}', 'banc', 'charge'::public.type_exercice, 'Disque sur les genoux, on cible le soléaire.'),
  ('Gainage planche', 'gainage-planche', 'abdominaux', array['lombaires'], 'tapis', 'temps'::public.type_exercice, 'Coudes sous les épaules, fessiers serrés, aucune cambrure.'),
  ('Gainage latéral', 'gainage-lateral', 'abdominaux', '{}', 'tapis', 'temps'::public.type_exercice, 'Hanche haute, corps aligné vu de face.'),
  ('Hollow hold', 'hollow-hold', 'abdominaux', '{}', 'tapis', 'temps'::public.type_exercice, 'Bas du dos plaqué au sol, bras et jambes tendus.'),
  ('Relevé de jambes suspendu', 'releve-de-jambes-suspendu', 'abdominaux', '{}', 'barre_traction', 'poids_du_corps'::public.type_exercice, 'Jambes tendues jusqu''à l''horizontale, pas de balancement.'),
  ('Relevé de genoux suspendu', 'releve-de-genoux-suspendu', 'abdominaux', '{}', 'barre_traction', 'poids_du_corps'::public.type_exercice, 'Genoux vers la poitrine, bassin qui s''enroule en fin de course.'),
  ('Crunch au sol', 'crunch-au-sol', 'abdominaux', '{}', 'tapis', 'poids_du_corps'::public.type_exercice, 'On décolle les omoplates, pas tout le dos, nuque relâchée.'),
  ('Crunch poulie haute', 'crunch-poulie-haute', 'abdominaux', '{}', 'poulie', 'charge'::public.type_exercice, 'À genoux, on enroule la colonne vertèbre par vertèbre.'),
  ('Rollout à la barre', 'rollout-a-la-barre', 'abdominaux', array['lombaires'], 'barre_olympique', 'poids_du_corps'::public.type_exercice, 'À genoux, barre qui roule loin devant, dos qui ne creuse jamais.'),
  ('Russian twist', 'russian-twist', 'abdominaux', '{}', 'kettlebell', 'poids_du_corps'::public.type_exercice, 'Pieds décollés, rotation qui vient du buste et non des bras.'),
  ('Mountain climber', 'mountain-climber', 'abdominaux', array['cardio'], 'tapis', 'temps'::public.type_exercice, 'Position de pompe, genoux qui alternent vite, bassin stable.'),
  ('Dead bug', 'dead-bug', 'abdominaux', '{}', 'tapis', 'poids_du_corps'::public.type_exercice, 'Bras et jambe opposés qui s''allongent, lombaires collées au sol.'),
  ('Pallof press', 'pallof-press', 'abdominaux', '{}', 'elastique', 'charge'::public.type_exercice, 'Élastique sur le côté, on résiste à la rotation : c''est un anti-mouvement.'),
  ('V-ups', 'v-ups', 'abdominaux', '{}', 'tapis', 'poids_du_corps'::public.type_exercice, 'Bras et jambes qui se rejoignent au-dessus du bassin.'),
  ('Extension lombaire au sol', 'extension-lombaire-au-sol', 'lombaires', array['fessiers'], 'tapis', 'poids_du_corps'::public.type_exercice, 'Buste décollé sans à-coup, regard vers le sol.'),
  ('Superman', 'superman', 'lombaires', array['fessiers'], 'tapis', 'temps'::public.type_exercice, 'Bras et jambes décollés en même temps, tenue du chrono.'),
  ('Bird dog', 'bird-dog', 'lombaires', array['abdominaux'], 'tapis', 'poids_du_corps'::public.type_exercice, 'Bras et jambe opposés à l''horizontale, bassin qui ne bascule pas.'),
  ('Corde à sauter', 'corde-a-sauter', 'cardio', array['mollets'], 'corde_a_sauter', 'temps'::public.type_exercice, 'Sauts bas, poignets qui tournent, coudes près du corps.'),
  ('Burpee', 'burpee', 'cardio', array['corps_entier'], 'poids_du_corps', 'poids_du_corps'::public.type_exercice, 'Poitrine au sol, saut avec les mains au-dessus de la tête.'),
  ('Burpee broad jump', 'burpee-broad-jump', 'cardio', array['corps_entier'], 'poids_du_corps', 'distance'::public.type_exercice, 'Burpee suivi d''un saut en longueur, on compte la distance parcourue.'),
  ('Wall balls', 'wall-balls', 'corps_entier', array['quadriceps', 'epaules'], 'medecine_ball', 'charge'::public.type_exercice, 'Squat complet puis lancer contre la cible, on rattrape en descendant.'),
  ('Sled push', 'sled-push', 'corps_entier', array['quadriceps', 'fessiers'], 'traineau', 'distance'::public.type_exercice, 'Bras tendus, buste incliné, petits pas rapides et continus.'),
  ('Sled pull', 'sled-pull', 'corps_entier', array['dos', 'ischios'], 'traineau', 'distance'::public.type_exercice, 'Tirage à la corde, recul régulier, dos plat.'),
  ('Sandbag lunges', 'sandbag-lunges', 'quadriceps', array['fessiers', 'corps_entier'], 'sac', 'distance'::public.type_exercice, 'Sac sur les épaules, genou arrière au sol à chaque pas.'),
  ('Ski erg', 'ski-erg', 'cardio', array['dos', 'abdominaux'], 'ski_erg', 'distance'::public.type_exercice, 'Extension complète de hanche à chaque tirage, bras qui finissent le long du corps.'),
  ('Rameur', 'rameur', 'cardio', array['dos', 'quadriceps'], 'rameur', 'distance'::public.type_exercice, 'Jambes, buste, bras dans cet ordre ; retour dans l''ordre inverse.'),
  ('Course à pied', 'course-a-pied', 'cardio', array['mollets', 'ischios'], 'poids_du_corps', 'distance'::public.type_exercice, 'Allure régulière, foulée courte, cadence élevée.'),
  ('Thruster', 'thruster', 'corps_entier', array['quadriceps', 'epaules'], 'barre_olympique', 'charge'::public.type_exercice, 'Front squat enchaîné à un développé, un seul mouvement fluide.'),
  ('Épaulé', 'epaule', 'corps_entier', array['quadriceps', 'dos'], 'barre_olympique', 'charge'::public.type_exercice, 'Tirage explosif puis passage sous la barre, coudes projetés vers l''avant.'),
  ('Épaulé-jeté', 'epaule-jete', 'corps_entier', array['epaules', 'quadriceps'], 'barre_olympique', 'charge'::public.type_exercice, 'Épaulé, puis impulsion des jambes pour envoyer la barre au-dessus de la tête.'),
  ('Arraché kettlebell', 'arrache-kettlebell', 'corps_entier', array['epaules', 'dos'], 'kettlebell', 'charge'::public.type_exercice, 'Un seul mouvement du sol au bras tendu, poignet qui pivote sans claquer.'),
  ('Turkish get-up', 'turkish-get-up', 'corps_entier', array['abdominaux', 'epaules'], 'kettlebell', 'charge'::public.type_exercice, 'Du sol à debout, kettlebell toujours à la verticale, regard dessus.'),
  ('Man maker', 'man-maker', 'corps_entier', array['pectoraux', 'epaules'], 'halteres', 'charge'::public.type_exercice, 'Pompe, rowing des deux côtés, puis développé debout : une seule répétition.'),
  ('Devil press', 'devil-press', 'corps_entier', array['epaules', 'cardio'], 'halteres', 'charge'::public.type_exercice, 'Burpee haltères en main puis passage direct au-dessus de la tête.'),
  ('Box jump', 'box-jump', 'quadriceps', array['mollets', 'cardio'], 'banc', 'poids_du_corps'::public.type_exercice, 'Réception complète sur la box avant l''extension, descente en marchant.'),
  ('Bear crawl', 'bear-crawl', 'corps_entier', array['abdominaux', 'epaules'], 'poids_du_corps', 'distance'::public.type_exercice, 'Genoux à deux centimètres du sol, déplacement bras et jambe opposés.'),
  ('Marche gobelet', 'marche-gobelet', 'corps_entier', array['abdominaux', 'quadriceps'], 'kettlebell', 'distance'::public.type_exercice, 'Kettlebell contre la poitrine, buste vertical, respiration régulière.')
on conflict (slug) where owner_id is null do update
  set nom = excluded.nom,
      groupe_principal = excluded.groupe_principal,
      groupes_secondaires = excluded.groupes_secondaires,
      equipement = excluded.equipement,
      type = excluded.type,
      instructions = excluded.instructions;
